titles:
    none: '無題'
    home: 'ホーム'
    login: 'ログイン'
    new_post: '新規投稿'
    search_post: 'コレクション検索'
    search_user: 'ユーザー検索'
    contact: 'お問い合わせ'
    new_registration: '新規登録'
    edit_registration: 'アカウント情報編集'

link_utils:
    top: 'トップページ'
    login: 'ログイン'
    logout: 'ログアウト'
    search_user: 'ユーザー検索'
    mypage: 'マイページ'
    new_registration: '新規登録'
    forget_password: 'パスワードを忘れてしまったら'
    confirmation_email_resent: '認証メールが届かない場合はこちら'
    contact: 'お問い合わせ'
    back: '戻る'

messages:
    logout_confirm: 'ログアウトしてよろしいですか？'
    delte_confirm: '本当に削除してよろしいですか？'
    post_not_found: 'このキーワードではまだ投稿がないみたいですね...'
    encourage_post: 'あなたが最初の投稿者になりましょう！'
    post_none: 'まだコレクションがありません'
    alone: 'これでは寂しいですね...'
    no_following_user: 'フォローしているユーザーはいません...'
    encourage_follow: '気の合う仲間を探してみましょう！'
    no_follower: 'フォロワーはまだいないようです...'
    no_likes: 'まだいいねしていません...'
    encourage_likes: 'あなたのお気に入りを探しに行きましょう！'
    has_account: 'アカウントをお持ちですか？'
    guest_account_edit_info: 'ゲストユーザーはアカウント情報を編集できません'

home_utils:
    hello: 'Hello Nature!'
    sub_copy: 'さあ、新しい世界を探しに行きましょう！'
    no_following_text: 'ユーザーをフォローしてタイムラインで投稿を確認しよう！'
    post_list: 'みんなのコレクション'
    user_search_placeholder: 'ユーザー検索'
    post_search_placeholder: 'キーワード'
    introductions:
        main: '石ころから宇宙まで、NateMateで共有しよう'
        sub1: '道ばたの花、飼っている動物、遠くの惑星、自分しか知らない景色...'
        sub2: 'NateMateは、そんなNature(自然)をデジタルに保存、公開できるSNSです'

post_utils:
    title: '新しいコレクション'
    select_image_file: '画像を選択'
    get_position_from_image: '画像から位置情報を取得'
    get_position_from_address: '住所から位置情報を取得'
    address_placeholder: '例)東京都渋谷区'
    title_placeholder: 'この写真にタイトルをつけましょう！(20字以内)'
    content_placeholder: 'この写真についてもっと教えてください！(140字以内)'
    submit_post: '投稿する！'
    likes_none: 'いいねはまだありません'
    position_none: '位置情報が登録されていません'

session_utils:
    login: 'ログイン'
    guest_login: 'おためしログイン'
    guest_user_id: 'guest@guest.com'
    guest_user_password: 'password'

registration_utils:
    new: '新規登録'
    edit: 'アカウント情報編集'
    select_image_file: '画像を選択'
    confirm_new_account: '登録する'
    confirm_edit: '更新する'
    validate_password_min_length: '(6文字以上)'


view_utils:
    website_name: 'NateMate'
    new_post: '新しいコレクション'
    collection: 'コレクション'
    post: '投稿'
    by: 'by'
    or: 'or'
    at: 'at:'
    collected: 'collected'
    more_view: 'さらに表示'
    more_view2: 'もっと見る'
    login: 'ログイン'
    post_list: 'コレクション'
    likes: 'いいね'
    likes_en: 'likes'
    like!: 'いいね！'
    follow: 'フォローする'
    following: 'フォロー中'
    following_en: 'following'
    follower: 'フォロワー'
    follower_en: 'followers'
    not_found: 'Not Found'
    search_result: '検索結果:'
    count: '件'
    my_map: 'Myマップ'
    new_arrival: '新着'
    time_line: 'タイムライン'
    search_user: 'ユーザー検索'
    account_delete: 'このアカウントを削除する'

contact_utils:
    title: 'お問い合わせ'
    email: 'Email: ohtukayoshi.yoshi@gmail.com'

footer_utils:
    describe: 'Copyright©︎2020 NateMate.com, All Rights Reserved.'

